mysite/mysite/apps/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:new_id>/', views.detail, name='detail'),
    path('<int:new_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('footballSite/', include('main.urls')),
]

mysite/mysite/apps/main/models.py
from django.db import models


#Модель последних новостей
class LatestNewsModel(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    content = models.TextField(verbose_name='Текст новости')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Последняя новость'
        verbose_name_plural = 'Последние новости'


#Модель комментариев
class Comment(models.Model):
    new = models.ForeignKey(LatestNewsModel, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name='Имя комментатора')
    text = models.TextField(verbose_name='Текст комментария')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

mysite/mysite/apps/main/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from .models import LatestNewsModel, Comment
from django.http import Http404, HttpResponseRedirect


def index(request):
    news = LatestNewsModel.objects.all()
    context = {'news': news}
    return render(request, 'main/list.html', context)


def detail(request, new_id):
    try:
        new = LatestNewsModel.objects.get(id=new_id)
    except:
        raise Http404('Страница не найдена')

    latest_comment_list = new.comment_set.order_by('-id')[:10]

    context = {'new': new, 'latest_comment_list': latest_comment_list}
    return render(request, 'main/detail.html', context)


def leave_comment(request, new_id):
    try:
        new = LatestNewsModel.objects.get(id=new_id)
    except:
        raise Http404('Страница не найдена')

    new.comment_set.create(name=request.POST['name'], text=request.POST['text'])
    return HttpResponseRedirect(reverse('main:detail', args=(new_id,)))

mysite/mysite/templates/base.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Главная{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
<a href="{% url 'main:index' %}">Главная</a>

{% block content %}
{% endblock content %}
  <script rel="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mysite/mysite/templates/main/detail.html
{% extends 'base.html' %}
{% block title %}{{ new.title }}{% endblock title %}

{% block content %}
  <h2>{{ new.title }}</h2><br>
  <p>{{ new.content }}</p><br>
  <em>{{ new.pub_date }}</em><br>

{% if latest_comment_list %}
  {% for c in latest_comment_list %}
  <p>{{ c.name }}</p><br>
  <p>{{ c.text }}</p><br>
  <em>{{ c.pub_date }}</em><br>
  {% endfor %}
  {% else %}
  Комментарии не найдены, станьте первым
{% endif %}

<div class="mb-3">
  <form action="{% url 'main:leave_comment' new.id %}" method="post">
    {% csrf_token %}
  <input type="text" placeholder="Ваше имя" name="name">
</div>
<div class="mb-3">
  <textarea name="text" placeholder="Текст комментария" cols="50" rows="5"></textarea>
</div>
<button type="submit">Оставить комментарий</button>
{% endblock %}

mysite/mysite/templates/main/list.html
{% extends 'base.html' %}
{% block title %}Последние новости{% endblock title %}

{% block content %}
{% for new in news %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <a href="{% url 'main:detail' new.id %}">{{ new.title }}</a>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}